Thes 2531: QRP by TaxCode API
credimi/ceres pull request #3
Opened 2024-08-13 14:10 UTC by anbonifacio

## Description
This PR adds an API to request QRP generation by tax code.

### Checklist

I confirm that before submitting this PR I have:

- [x] successfully run `cargo build` on my local environment
- [x] formatted all Rust files with `cargo fmt`
- [x] checked all code hints with `cargo clippy`
- [x] successfully run `cargo test` on my local environment
- [ ] successfully run automatic tests in QA (namespace `xx-yyy`)
- [ ] successfully run manual tests in QA (namespace `xx-yyy`)
- [x] updated the project README with new relevant information
- [ ] added new documentation for Backstage
    - [ ] updated resources (`catalog-info.yaml`, `providesApis`, `consumesApi`, `mkdocs.yml`) with proper information
    - [x] updated file(s) under `docs/`
        - [ ] with a comprehensive description of the new features
        - [x] with useful development and testing commands
- [ ] updated Confluence page with new relevant information

## Notes for reviewer(s)

## Release notes

2024-08-14 08:53 UTC, GiaMoscariello reviewed
Just a minor comment 😬

2024-08-14 08:53 UTC, GiaMoscariello commented on src/qrp/mod.rs
> +            QrpGeneration::ByVatNumber(vat_number) => write!(f, "vat_number: {}", vat_number),
```suggestion
            QrpGeneration::ByVatNumber(vat_number) => write!(f, "vat_code: {}", vat_number),
```
We usually use this naming ☝️

2024-08-14 09:14 UTC, albx79 commented on src/routes.rs
> +    let db = app_data.db.clone();
do you need to clone everything? You got `app_data` by value so I think you can just move out or use references.

2024-08-14 09:14 UTC, albx79 commented on src/routes.rs
> +    let tax_code = ByTaxCode(body.tax_code.clone());
you made a powerful thing, that can be either by tax code or by vat number. Use the power of the thing you created! this endpoint, with a bit of serde magic, could accept a json that contains either `"tax_code":` or `"vat_number":`, which would be awesome!

2024-08-14 09:14 UTC, albx79 commented on src/routes.rs
> +    };
if you factor out this bit, too, from here and from `generate_qrp_by_vat_number`, you can keep both simpler and DRYer. I like controller methods to be super-minimal because, as you have noticed, it's almost impossible to write an integration test.

2024-08-19 09:00 UTC, albx79 requested changes

2024-08-19 09:00 UTC, albx79 commented on src/aws/mod.rs
> +            tags.push(format!("vat_code={}", vat_code));
for tagging we use camelCase, e.g. https://eu-west-1.console.aws.amazon.com/s3/object/it-bancacfplus-prod-documentale?region=eu-west-1&bucketType=general&prefix=01111000459/Financing/1717489094_01111000459_412132/Guarantee/ALLEGATO4-signed.pdf

2024-08-19 09:30 UTC, albx79 reviewed
one last little change (if I haven't missed anything else 🤞 )

2024-08-19 09:30 UTC, albx79 commented on src/aws/aws_s3.rs
> +        assert_eq!(tax_tags.file_type, "Xml");
speaking of tags, I don't find "fileType" particularly useful (we already have the filename extension). Something more useful could be `documentType` with values `QRP_XML,` and `QRP_PDF`.

2024-08-19 13:24 UTC, albx79 approved these changes

2024-08-19 13:28 UTC, merged